// Code generated by "stringer -type=ParseType"; DO NOT EDIT.

package tre

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParseErr-0]
	_ = x[ParseClass-1]
	_ = x[ParseConcat-2]
	_ = x[ParseAlt-3]
	_ = x[ParseStar-4]
	_ = x[ParsePlus-5]
}

const _ParseType_name = "ParseErrParseClassParseConcatParseAltParseStarParsePlus"

var _ParseType_index = [...]uint8{0, 8, 18, 29, 37, 46, 55}

func (i ParseType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ParseType_index)-1 {
		return "ParseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParseType_name[_ParseType_index[idx]:_ParseType_index[idx+1]]
}
