// Code generated by "stringer -type=TokType"; DO NOT EDIT.

package tre

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokErr-0]
	_ = x[TokAlt-1]
	_ = x[TokStar-2]
	_ = x[TokPlus-3]
	_ = x[TokOparen-4]
	_ = x[TokCparen-5]
	_ = x[TokDot-6]
	_ = x[TokChar-7]
	_ = x[TokClass-8]
}

const _TokType_name = "TokErrTokAltTokStarTokPlusTokOparenTokCparenTokDotTokCharTokClass"

var _TokType_index = [...]uint8{0, 6, 12, 19, 26, 35, 44, 50, 57, 65}

func (i TokType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokType_index)-1 {
		return "TokType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokType_name[_TokType_index[idx]:_TokType_index[idx+1]]
}
